
ALTER TABLE chat
    ADD COLUMN last_message VARCHAR(500) NOT NULL DEFAULT '';

ALTER TABLE chat
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE message
    ADD COLUMN status VARCHAR(30);
